

-- =========================================================================
-- 1. TAO ROLE VA CAP QUYEN CHO ROLE
-- =========================================================================
CREATE ROLE ROLE_USERS;
GRANT CREATE SESSION TO ROLE_USERS;
-- Role users still needs to see session info for force logout check
GRANT SELECT ON SYS.V_$SESSION TO ROLE_USERS;

-- =========================================================================
-- 2. TAO BANG (TABLES)
-- =========================================================================

-- 2.1 Bang CATEGORIES (Danh muc san pham)
CREATE TABLE CATEGORIES (
    CATEGORY_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME NVARCHAR2(100) NOT NULL
);

-- 2.2 Bang USERS (Nguoi dung ung dung)

CREATE TABLE USERS (
    USER_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_NAME   VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(100),
    ADDRESS     NVARCHAR2(100),
    IS_LOCKED   NUMBER(1) DEFAULT 0,
    FACE_IMG    BLOB,
    QR_CODE     VARCHAR2(255)
);

-- 2.3 Bang PRODUCTS (San pham)
CREATE TABLE PRODUCTS (
    PRODUCT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRODUCT_NAME  NVARCHAR2(100) NOT NULL,
    CATEGORY_ID   NUMBER NOT NULL,
    QUANTITY      NUMBER,
    PRICE         NUMBER,
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORIES(CATEGORY_ID)
);

-- 2.4 Bang ORDERS (Don hang)
CREATE TABLE ORDERS (
    ORDER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    ORDER_DATE       DATE DEFAULT SYSDATE,
    CONTACT_NAME     NVARCHAR2(100) NOT NULL,
    CONTACT_PHONE    VARCHAR2(20) NOT NULL,
    SHIPPING_ADDRESS NVARCHAR2(255) NOT NULL,
    PAYMENT_METHOD   NVARCHAR2(50) NOT NULL,
    STATUS           NVARCHAR2(20) DEFAULT N'Chưa xử lý'
                     CHECK (STATUS IN (N'Chưa xử lý', N'Đang xử lý', N'Đang giao', N'Hoàn tất', N'Hủy')),
    CANCEL_REASON    NVARCHAR2(255),
    IS_SIGNED        NUMBER(1) DEFAULT 0,
    SIGNATURE_DATA   CLOB,
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 2.5 Bang ORDER_DETAILS (Chi tiet don hang)
CREATE TABLE ORDER_DETAILS (
    ORDER_ID    NUMBER NOT NULL,
    PRODUCT_ID  NUMBER NOT NULL,
    QUANTITY    NUMBER DEFAULT 1,
    PRICE       NUMBER,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_OD_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_OD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- =========================================================================
-- 3. CHEN DU LIEU MAU (INSERT DATA)
-- =========================================================================

-- Insert Categories
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES (N'Giày thể thao');
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES (N'Giày da');
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES (N'Sandal');
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES (N'Dép');

-- Insert Products
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Nike Air Max 270', 1, 50, 3500000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Adidas Ultraboost', 1, 40, 4200000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Giày da nam Oxford', 2, 20, 2500000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Giày da nữ cao gót', 2, 30, 1800000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Sandal quai chéo nữ', 3, 60, 700000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Sandal nam đi biển', 3, 40, 600000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Dép lê Adidas', 4, 100, 450000);
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE) VALUES (N'Dép Crocs chính hãng', 4, 80, 800000);

COMMIT;

-- =========================================================================
-- 4. PACKAGE MA HOA (ENCRYPTION)
-- =========================================================================
CREATE OR REPLACE PACKAGE NAM_DOAN.ENCRYPT_PKG AS
    FUNCTION F_ENCRYPT_DB(p_input VARCHAR2, p_key NUMBER) RETURN VARCHAR2;
    PROCEDURE P_REGISTER_USER(
        p_username VARCHAR2,
        p_password VARCHAR2,
        p_email    VARCHAR2,
        p_addr     NVARCHAR2
    );
END ENCRYPT_PKG;
/

CREATE OR REPLACE PACKAGE BODY NAM_DOAN.ENCRYPT_PKG AS

    -- Ham ma hoa
    FUNCTION F_ENCRYPT_DB(p_input VARCHAR2, p_key NUMBER) RETURN VARCHAR2 IS
        alphabet VARCHAR2(400) := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*()-_=+.';
        result   VARCHAR2(4000) := '';
        c        VARCHAR2(1);
        pos      NUMBER;
        new_pos  NUMBER;
        ln       PLS_INTEGER := NVL(LENGTH(p_input),0);
    BEGIN
        IF p_input IS NULL THEN
            RETURN NULL;
        END IF;

        FOR i IN 1..ln LOOP
            c := SUBSTR(p_input, i, 1);
            pos := INSTR(alphabet, c);
            IF pos > 0 THEN
                new_pos := MOD(pos * p_key, LENGTH(alphabet));
                IF new_pos = 0 THEN
                    new_pos := LENGTH(alphabet);
                END IF;
                result := result || SUBSTR(alphabet, new_pos, 1);
            ELSE
                result := result || c;
            END IF;
        END LOOP;

        RETURN result;
    END F_ENCRYPT_DB;

    -- Thu tuc dang ky user moi (Ma hoa > Tao User Oracle > Luu Database)
    PROCEDURE P_REGISTER_USER(
        p_username VARCHAR2,
        p_password VARCHAR2,
        p_email    VARCHAR2,
        p_addr     NVARCHAR2
    ) IS
        v_user_encrypted VARCHAR2(4000);
        v_pass_encrypted VARCHAR2(4000);
        v_exists NUMBER;
        v_sql VARCHAR2(4000);
    BEGIN
        IF p_username IS NULL OR p_password IS NULL THEN
            RAISE_APPLICATION_ERROR(-20011, 'Username/password null');
        END IF;

        -- Ma hoa tang 2 
        v_user_encrypted := F_ENCRYPT_DB(p_username, 9);
        v_pass_encrypted := F_ENCRYPT_DB(p_password, 9);

        -- Kiem tra ton tai
        SELECT COUNT(*) INTO v_exists
        FROM NAM_DOAN.USERS
        WHERE USER_NAME = v_user_encrypted;

        IF v_exists > 0 THEN
            RAISE_APPLICATION_ERROR(-20012, 'Ten nguoi dung da ton tai!');
        END IF;

        -- Tao Oracle User (dung quoted identifier de giu ky tu dac biet)
        v_sql := 'CREATE USER "' || v_user_encrypted || '" IDENTIFIED BY "' || REPLACE(v_pass_encrypted, '"', '""') || '"';
        EXECUTE IMMEDIATE v_sql;

        -- Cap role mac dinh (ROLE_USERS)
        EXECUTE IMMEDIATE 'GRANT ROLE_USERS TO "' || v_user_encrypted || '"';

        -- Luu vao bang USERS
        INSERT INTO NAM_DOAN.USERS (USER_NAME, PASSWORD, EMAIL, ADDRESS)
        VALUES (v_user_encrypted, v_pass_encrypted, p_email, p_addr);

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20010, 'Loi khi dang ky user: ' || SQLERRM);
    END P_REGISTER_USER;

END ENCRYPT_PKG;
/

-- Cap quyen thuc thi goi ma hoa cho Role
GRANT EXECUTE ON NAM_DOAN.ENCRYPT_PKG TO ROLE_USERS;

-- 4.2 PACKAGE MA HOA FILE (DES)
CREATE OR REPLACE PACKAGE NAM_DOAN.DES_PKG AS
    PROCEDURE encrypt_file(
        p_input  IN BLOB,
        p_key    IN VARCHAR2,
        p_output OUT BLOB
    );
    PROCEDURE decrypt_file(
        p_input  IN BLOB,
        p_key    IN VARCHAR2,
        p_output OUT BLOB
    );
END DES_PKG;
/

CREATE OR REPLACE PACKAGE BODY NAM_DOAN.DES_PKG AS

    -- Helper converts string key to raw
    FUNCTION get_raw_key(p_key VARCHAR2) RETURN RAW IS
    BEGIN
        -- Convert string key to RAW. 
        -- Note: DES 64-bit key (8 bytes). 
        -- User provides 8-char string -> 8 bytes.
        RETURN UTL_RAW.CAST_TO_RAW(p_key);
    END;

    PROCEDURE encrypt_file(
        p_input  IN BLOB,
        p_key    IN VARCHAR2,
        p_output OUT BLOB
    ) IS
        v_key_raw     RAW(128);
    BEGIN
        v_key_raw := get_raw_key(p_key);
        
        -- Initialize output BLOB
        DBMS_LOB.CREATETEMPORARY(p_output, TRUE);

        -- Encrypt
        -- DES + CBC + PKCS5
        DBMS_CRYPTO.ENCRYPT(
            dst => p_output,
            src => p_input,
            typ => DBMS_CRYPTO.ENCRYPT_DES + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key_raw,
            iv  => NULL -- Default IV (all zeros) for simplicity matching simple usages
        );
    END;

    PROCEDURE decrypt_file(
        p_input  IN BLOB,
        p_key    IN VARCHAR2,
        p_output OUT BLOB
    ) IS
        v_key_raw     RAW(128);
    BEGIN
        v_key_raw := get_raw_key(p_key);

        -- Initialize output BLOB
        DBMS_LOB.CREATETEMPORARY(p_output, TRUE);

        -- Decrypt
        DBMS_CRYPTO.DECRYPT(
            dst => p_output,
            src => p_input,
            typ => DBMS_CRYPTO.ENCRYPT_DES + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
            key => v_key_raw,
            iv  => NULL
        );
    END;

END DES_PKG;
/

-- Cap quyen thuc thi goi ma hoa DES cho Role
GRANT EXECUTE ON NAM_DOAN.DES_PKG TO ROLE_USERS;



-- =========================================================================
-- 5. FUNCTION HE THONG (CHECK USER, SESSION, LAY ID)
-- =========================================================================

-- Kiem tra user ton tai trong bang USERS
CREATE OR REPLACE FUNCTION F_CHECK_USERS_EXISTS(p_username IN VARCHAR2)
RETURN NUMBER
AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM NAM_DOAN.USERS
    WHERE USER_NAME = p_username;
    RETURN v_count;
END;
/

-- Lay ID user theo ten dang nhap
CREATE OR REPLACE FUNCTION F_GET_USER_ID_BY_NAME(p_username IN VARCHAR2)
RETURN NUMBER
AS
    v_userid NUMBER;
BEGIN
    SELECT USER_ID INTO v_userid
    FROM NAM_DOAN.USERS
    WHERE USER_NAME = p_username;
    RETURN v_userid;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- Kiem tra trang thai Session (Active/Inactive/Killed)
CREATE OR REPLACE FUNCTION F_IS_SESSION_ACTIVE(
    p_sid IN VARCHAR2,
    p_serial IN VARCHAR2
)
RETURN NUMBER
AS
    v_count NUMBER;
BEGIN
    -- Kiem tra xem cap SID va SERIAL# nay con ton tai khong
    SELECT COUNT(*) INTO v_count
    FROM SYS.V_$SESSION
    WHERE SID = TO_NUMBER(p_sid)
      AND SERIAL# = TO_NUMBER(p_serial);

    RETURN CASE WHEN v_count > 0 THEN 1 ELSE 0 END;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0; 
END;
/

-- Lay SID cua session hien tai (User dang login)
CREATE OR REPLACE FUNCTION F_GET_SESSION_SID(p_username VARCHAR2)
RETURN NUMBER
AS
    v_sid NUMBER;
BEGIN
    SELECT sid INTO v_sid
    FROM SYS.V_$SESSION
    WHERE username = UPPER(p_username)
      AND audsid = USERENV('SESSIONID');
    RETURN v_sid;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN -1;
END;
/

-- Lay Serial cua session hien tai
CREATE OR REPLACE FUNCTION F_GET_SESSION_SERIAL(p_username VARCHAR2)
RETURN NUMBER
AS
    v_serial NUMBER;
BEGIN
    SELECT serial# INTO v_serial
    FROM SYS.V_$SESSION
    WHERE username = UPPER(p_username)
      AND audsid = USERENV('SESSIONID');
    RETURN v_serial;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN -1;
END;
/

-- Kiem tra trang thai khoa cua tai khoan (IS_LOCKED)
CREATE OR REPLACE FUNCTION NAM_DOAN.F_CHECK_IS_LOCKED (
    p_username IN VARCHAR2
) RETURN NUMBER IS
    v_is_locked NUMBER;
BEGIN
    SELECT IS_LOCKED INTO v_is_locked
    FROM USERS
    WHERE USER_NAME = p_username;
    
    RETURN v_is_locked;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0; 
END;
/

-- Cap quyen thuc thi cac Function cho Role
GRANT EXECUTE ON NAM_DOAN.F_CHECK_IS_LOCKED TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.F_IS_SESSION_ACTIVE TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.F_GET_SESSION_SID TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.F_GET_SESSION_SERIAL TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.F_GET_USER_ID_BY_NAME TO ROLE_USERS;


-- =========================================================================
-- 6. STORED PROCEDURES - QUAN LY HE THONG (SESSION, DEVICE)
-- =========================================================================

-- Lay thong tin session hien tai
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GET_CURRENT_SESSION_INFO(p_rc OUT SYS_REFCURSOR)
AUTHID DEFINER
AS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'SELECT sid, serial# FROM SYS.V_$SESSION WHERE audsid = USERENV(''SESSIONID'')';
    OPEN p_rc FOR v_sql;
END;
/

-- Hien thi danh sach thiet bi dang dang nhap cua user
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_LIST_USER_DEVICES(
    p_rc OUT SYS_REFCURSOR
)
AUTHID DEFINER
AS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'SELECT MACHINE AS DEVICE_NAME, PROGRAM AS APP_NAME, LOGON_TIME, STATUS ' ||
             'FROM SYS.V_$SESSION WHERE USERNAME = SYS_CONTEXT(''USERENV'', ''SESSION_USER'') ' ||
             'ORDER BY LOGON_TIME DESC';
    OPEN p_rc FOR v_sql;
END;
/

-- Logout thiet bi hien tai
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_LOGOUT_CURRENT_DEVICE(
    p_username IN VARCHAR2
)
AUTHID DEFINER
AS
    v_sid    NUMBER;
    v_serial NUMBER;
    v_sql    VARCHAR2(1000);
BEGIN
    -- Lay session hien tai (Dung Dynamic SQL de bypass compile-time privilege check)
    v_sql := 'SELECT sid, serial# FROM SYS.V_$SESSION WHERE username = UPPER(:1) AND audsid = USERENV(''SESSIONID'')';
    
    BEGIN
        EXECUTE IMMEDIATE v_sql INTO v_sid, v_serial USING p_username;
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN RETURN;
        WHEN OTHERS THEN RETURN;
    END;

    -- Kill Session
    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || v_sid || ',' || v_serial || ''' IMMEDIATE';
    
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Logout tat ca thiet bi
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_LOGOUT_ALL_DEVICE(
    p_username IN VARCHAR2
)
AUTHID DEFINER
AS
BEGIN
    FOR rec IN (
        SELECT sid, serial#
        FROM SYS.V_$SESSION
        WHERE username = UPPER(p_username)
          AND status IN ('ACTIVE', 'INACTIVE')
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || rec.sid || ',' || rec.serial# || ''' IMMEDIATE';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- Logout thiet bi duoc chon
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_LOGOUT_SELECTED_DEVICE(
    p_username IN VARCHAR2,
    p_machine  IN VARCHAR2
)
AUTHID DEFINER
AS
BEGIN
    FOR rec IN (
        SELECT sid, serial#
        FROM SYS.V_$SESSION
        WHERE username = UPPER(p_username)
          AND machine LIKE '%' || p_machine || '%'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || rec.sid || ',' || rec.serial# || ''' IMMEDIATE';
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- Cap quyen cac thu tuc quan ly thiet bi cho Role
GRANT EXECUTE ON NAM_DOAN.P_LIST_USER_DEVICES TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_GET_CURRENT_SESSION_INFO TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_LOGOUT_SELECTED_DEVICE TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_LOGOUT_ALL_DEVICE TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_LOGOUT_CURRENT_DEVICE TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_REVOKE_PERMISSION_FROM_ROLE TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_REVOKE_ROLE_FROM_USER TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_CHECK_ROLE_PERMISSION TO ROLE_USERS;


-- =========================================================================
-- 7. STORED PROCEDURES - QUAN LY DU LIEU (SAN PHAM, DON HANG)
-- =========================================================================

-- Function lay tat ca Order (tra ve Cursor)
CREATE OR REPLACE FUNCTION F_GET_ALL_ORDERS
RETURN SYS_REFCURSOR
AS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT ORDER_ID,
               USER_ID,
               ORDER_DATE,
               CONTACT_NAME,
               CONTACT_PHONE,
               SHIPPING_ADDRESS,
               PAYMENT_METHOD,
               STATUS,
               CANCEL_REASON
        FROM NAM_DOAN.ORDERS
        ORDER BY ORDER_ID DESC;
    RETURN rc;
END;
/

-- Function lay Order theo UserID
CREATE OR REPLACE FUNCTION F_GET_ORDERS_BY_USER(p_user_id NUMBER)
RETURN SYS_REFCURSOR
AS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT ORDER_ID,
               USER_ID,
               ORDER_DATE,
               CONTACT_NAME,
               CONTACT_PHONE,
               SHIPPING_ADDRESS,
               PAYMENT_METHOD,
               STATUS,
               CANCEL_REASON
        FROM NAM_DOAN.ORDERS
        WHERE USER_ID = p_user_id
        ORDER BY ORDER_DATE DESC;
    RETURN rc;
END;
/

-- Function lay chi tiet don hang
CREATE OR REPLACE FUNCTION F_GET_ORDER_DETAILS(p_order_id NUMBER)
RETURN SYS_REFCURSOR
AS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT od.ORDER_ID,
               od.PRODUCT_ID,
               p.PRODUCT_NAME,
               od.QUANTITY,
               od.PRICE
        FROM NAM_DOAN.ORDER_DETAILS od
        JOIN NAM_DOAN.PRODUCTS p
            ON od.PRODUCT_ID = p.PRODUCT_ID
        WHERE od.ORDER_ID = p_order_id;
    RETURN rc;
END;
/

-- Procedure lay tat ca san pham
CREATE OR REPLACE PROCEDURE P_GET_ALL_PRODUCTS(
    p_rc OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_rc FOR
        SELECT PRODUCT_ID   AS ProductId,
               PRODUCT_NAME AS ProductName,
               CATEGORY_ID  AS CategoryId,
               QUANTITY     AS Quantity,
               PRICE        AS Price
        FROM NAM_DOAN.PRODUCTS
        ORDER BY PRODUCT_ID;
END;
/

-- Procedure Them San pham
CREATE OR REPLACE PROCEDURE P_INSERT_PRODUCT(
    p_name        IN NVARCHAR2,
    p_category_id IN NUMBER,
    p_quantity    IN NUMBER,
    p_price       IN NUMBER
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO NAM_DOAN.PRODUCTS (PRODUCT_NAME, CATEGORY_ID, QUANTITY, PRICE)
    VALUES (p_name, p_category_id, p_quantity, p_price);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20021, 'Error insert product: ' || SQLERRM);
END;
/

-- Procedure Cap nhat San pham
CREATE OR REPLACE PROCEDURE P_UPDATE_PRODUCT(
    p_id          IN NUMBER,
    p_name        IN NVARCHAR2,
    p_category_id IN NUMBER,
    p_quantity    IN NUMBER,
    p_price       IN NUMBER
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    UPDATE NAM_DOAN.PRODUCTS
    SET PRODUCT_NAME = p_name,
        CATEGORY_ID  = p_category_id,
        QUANTITY     = p_quantity,
        PRICE        = p_price
    WHERE PRODUCT_ID = p_id;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20022, 'Error update product: ' || SQLERRM);
END;
/

-- Procedure Xoa San pham
CREATE OR REPLACE PROCEDURE P_DELETE_PRODUCT(
    p_id IN NUMBER
)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    DELETE FROM NAM_DOAN.PRODUCTS WHERE PRODUCT_ID = p_id;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20023, 'Error delete product: ' || SQLERRM);
END;
/

-- Procedure Tao Don hang moi
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_CREATE_ORDER (
    p_user_id        IN NUMBER,
    p_contact_name   IN NVARCHAR2,
    p_phone          IN VARCHAR2,
    p_address        IN NVARCHAR2,
    p_payment_method IN NVARCHAR2, 
    p_order_id       OUT NUMBER
) IS
BEGIN
    INSERT INTO ORDERS (
        USER_ID, CONTACT_NAME, CONTACT_PHONE, SHIPPING_ADDRESS, 
        PAYMENT_METHOD, STATUS, ORDER_DATE
    )
    VALUES (
        p_user_id, p_contact_name, p_phone, p_address, 
        p_payment_method, N'Chưa xử lý', SYSDATE
    )
    RETURNING ORDER_ID INTO p_order_id;
END;
/

-- Procedure Them chi tiet don hang
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_ADD_ORDER_DETAIL (
    p_order_id   IN NUMBER,
    p_product_id IN NUMBER,
    p_quantity   IN NUMBER
) IS
    v_price NUMBER;
BEGIN
    -- Lay gia hien tai cua san pham
    SELECT PRICE INTO v_price FROM PRODUCTS WHERE PRODUCT_ID = p_product_id;

    INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE)
    VALUES (p_order_id, p_product_id, p_quantity, v_price);
    
    -- Tru ton kho
    UPDATE PRODUCTS SET QUANTITY = QUANTITY - p_quantity WHERE PRODUCT_ID = p_product_id;
END;
/

-- Procedure Cap nhat chu ky so don hang
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_UPDATE_ORDER_SIGNATURE (
    p_order_id       IN NUMBER,
    p_signature_data IN CLOB -- Dung CLOB vi chuoi ky Base64 dai
) IS
BEGIN
    UPDATE ORDERS
    SET IS_SIGNED = 1,               -- Danh dau da ky
        SIGNATURE_DATA = p_signature_data -- Luu chuoi ky
    WHERE ORDER_ID = p_order_id;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Cap quyen truy cap du lieu san pham/don hang cho Role
GRANT SELECT ON NAM_DOAN.PRODUCTS TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_PRODUCTS TO ROLE_USERS;
GRANT EXECUTE ON F_GET_ORDERS_BY_USER TO ROLE_USERS;
GRANT EXECUTE ON F_GET_ORDER_DETAILS TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_CREATE_ORDER TO ROLE_USERS;
GRANT EXECUTE ON NAM_DOAN.P_ADD_ORDER_DETAIL TO ROLE_USERS; 


-- =========================================================================
-- 8. STORED PROCEDURES - QUAN LY USER (ADMIN)
-- =========================================================================

-- Lay tat ca User (trong bang USERS cua ung dung)
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GET_ALL_USERS (
    p_cursor OUT SYS_REFCURSOR
) 
IS
BEGIN
    OPEN p_cursor FOR
    SELECT 
        USER_ID, 
        USER_NAME, 
        PASSWORD, 
        EMAIL, 
        ADDRESS, 
        IS_LOCKED
    FROM USERS
    ORDER BY USER_ID ASC;
END;
/

-- Cap nhat trang thai khoa User (Ung dung)
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_UPDATE_USER_STATUS (
    p_user_id IN NUMBER,
    p_status IN NUMBER -- 1: Khoa, 0: Mo
) IS
BEGIN
    UPDATE USERS 
    SET IS_LOCKED = p_status 
    WHERE USER_ID = p_user_id;
    COMMIT;
END;
/

-- Xoa User Ung dung (Xoa ca du lieu lien quan)
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_DELETE_APP_USER (
    p_user_id IN NUMBER
) IS
BEGIN
    -- 1. Xoa chi tiet don hang
    DELETE FROM ORDER_DETAILS WHERE ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE USER_ID = p_user_id);

    -- 2. Xoa don hang
    DELETE FROM ORDERS WHERE USER_ID = p_user_id;

    -- 3. Xoa User
    DELETE FROM USERS WHERE USER_ID = p_user_id;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- =========================================================================
-- 9. STORED PROCEDURES - QUAN LY USER ORACLE & TABLESPACE (ADMIN CSDL)
-- =========================================================================

-- Tao User Oracle (Authid Definer) - Can quyen DBA
CREATE OR REPLACE PROCEDURE P_CREATE_USER_ACCOUNT(
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
)
AUTHID DEFINER
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER "' || p_username || '" IDENTIFIED BY "' || REPLACE(p_password,'"','""') || '"';
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Khong the tao user: ' || SQLERRM);
END;
/

-- Cap quyen Oracle co ban cho user
CREATE OR REPLACE PROCEDURE P_GRANT_PRIVILEGES_USER(
    p_username IN VARCHAR2
)
AUTHID DEFINER
AS
BEGIN
    EXECUTE IMMEDIATE 'GRANT ROLE_USERS TO "' || p_username || '"';
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Khong the cap quyen: ' || SQLERRM);
END;
/

-- Khoa tai khoan Oracle
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_LOCK_ORACLE_USER (
    p_username IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'ALTER USER "' || p_username || '" ACCOUNT LOCK';
END;
/

-- Mo khoa tai khoan Oracle
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_UNLOCK_ORACLE_USER (
    p_username IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'ALTER USER "' || p_username || '" ACCOUNT UNLOCK';
END;
/

-- Xoa tai khoan Oracle
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_DROP_ORACLE_USER (
    p_username IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'DROP USER "' || p_username || '" CASCADE';
END;
/

-- Tao Tablespace
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_CREATE_TABLESPACE (
    p_tablespace_name IN VARCHAR2,
    p_file_name       IN VARCHAR2, -- VD: data_01.dbf
    p_size_mb         IN NUMBER    -- MB
) IS
    v_sql VARCHAR2(1000);
    v_path VARCHAR2(200) := 'C:\APP\RINFU\PRODUCT\23AI\ORADATA\FREE\FREEPDB1\'; 
BEGIN
    v_sql := 'CREATE TABLESPACE ' || p_tablespace_name || 
             ' DATAFILE ''' || v_path || p_file_name || ''' SIZE ' || p_size_mb || 'M';
    EXECUTE IMMEDIATE v_sql;
END;
/

-- Cap Quota cho User tren Tablespace
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GRANT_QUOTA (
    p_username        IN VARCHAR2,
    p_tablespace_name IN VARCHAR2,
    p_size_mb         IN NUMBER 
) IS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'ALTER USER "' || p_username || '" QUOTA ' || p_size_mb || 'M ON ' || p_tablespace_name;
    EXECUTE IMMEDIATE v_sql;
END;
/


-- =========================================================================
-- 10. TINH NANG PHAN QUYEN (AUTHORIZATION)
-- =========================================================================

-- 10.1 Lay danh sach tat ca cac bang cua user hien tai
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GET_ALL_TABLES (
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR
        SELECT table_name 
        FROM user_tables
        ORDER BY table_name;
END;
/

-- 10.2 Lay danh sach tat ca User trong he thong Oracle
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GET_ALL_DB_USERS (
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR
        SELECT username 
        FROM all_users 
        WHERE username NOT IN ('SYS', 'SYSTEM', 'NAM_DOAN', 'OUTLN', 'DBSNMP') 
        ORDER BY username;
END;
/

-- 10.3 Cap quyen (GRANT) cho User tren Bang cu the
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GRANT_PERMISSION (
    p_user      IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    IN NUMBER, -- 1: Cap quyen, 0: Bo qua (1: Grant, 0: Skip)
    p_insert    IN NUMBER,
    p_update    IN NUMBER,
    p_delete    IN NUMBER
) AUTHID CURRENT_USER
IS
BEGIN
    IF p_select = 1 THEN 
        EXECUTE IMMEDIATE 'GRANT SELECT ON NAM_DOAN.' || p_table || ' TO "' || p_user || '"'; 
    END IF;
    IF p_insert = 1 THEN 
        EXECUTE IMMEDIATE 'GRANT INSERT ON NAM_DOAN.' || p_table || ' TO "' || p_user || '"'; 
    END IF;
    IF p_update = 1 THEN 
        EXECUTE IMMEDIATE 'GRANT UPDATE ON NAM_DOAN.' || p_table || ' TO "' || p_user || '"'; 
    END IF;
    IF p_delete = 1 THEN 
        EXECUTE IMMEDIATE 'GRANT DELETE ON NAM_DOAN.' || p_table || ' TO "' || p_user || '"'; 
    END IF;
END;
/

-- 10.4 Thu hoi quyen (REVOKE) cua User tren Bang cu the
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_REVOKE_PERMISSION (
    p_user      IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    IN NUMBER,
    p_insert    IN NUMBER,
    p_update    IN NUMBER,
    p_delete    IN NUMBER
) AUTHID CURRENT_USER
IS
BEGIN
    IF p_select = 1 THEN 
        BEGIN 
            EXECUTE IMMEDIATE 'REVOKE SELECT ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; 
        EXCEPTION WHEN OTHERS THEN NULL; 
        END; 
    END IF;
    IF p_insert = 1 THEN 
        BEGIN 
            EXECUTE IMMEDIATE 'REVOKE INSERT ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; 
        EXCEPTION WHEN OTHERS THEN NULL; 
        END; 
    END IF;
    IF p_update = 1 THEN 
        BEGIN 
            EXECUTE IMMEDIATE 'REVOKE UPDATE ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; 
        EXCEPTION WHEN OTHERS THEN NULL; 
        END; 
    END IF;
    IF p_delete = 1 THEN 
        BEGIN 
            EXECUTE IMMEDIATE 'REVOKE DELETE ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; 
        EXCEPTION WHEN OTHERS THEN NULL; 
        END; 
    END IF;
END;
/

-- 10.5 Tao Role moi de nhom cac quyen lai
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_CREATE_ROLE (
    p_role_name IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE "' || p_role_name || '"';
END;
/

-- 10.6 Cap quyen cho Role (tuong tu cap cho User)
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GRANT_PERMISSION_TO_ROLE (
    p_role      IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    IN NUMBER,
    p_insert    IN NUMBER,
    p_update    IN NUMBER,
    p_delete    IN NUMBER
) AUTHID CURRENT_USER
IS
BEGIN
    -- Su dung lai procedure P_GRANT_PERMISSION
    NAM_DOAN.P_GRANT_PERMISSION(p_role, p_table, p_select, p_insert, p_update, p_delete);
END;
/

-- 10.6.1 Thu hoi quyen tu Role
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_REVOKE_PERMISSION_FROM_ROLE (
    p_role      IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    IN NUMBER,
    p_insert    IN NUMBER,
    p_update    IN NUMBER,
    p_delete    IN NUMBER
) AUTHID CURRENT_USER
IS
BEGIN
    -- Su dung lai procedure P_REVOKE_PERMISSION
    NAM_DOAN.P_REVOKE_PERMISSION(p_role, p_table, p_select, p_insert, p_update, p_delete);
END;
/

-- 10.7 Gan Role cho User
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GRANT_ROLE_TO_USER (
    p_role_name IN VARCHAR2,
    p_username  IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'GRANT "' || p_role_name || '" TO "' || p_username || '"';
END;
/

-- 10.7.1 Thu hoi Role khoi User
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_REVOKE_ROLE_FROM_USER (
    p_role_name IN VARCHAR2,
    p_username  IN VARCHAR2
) AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'REVOKE "' || p_role_name || '" FROM "' || p_username || '"';
END;
/

-- 10.8 Lay danh sach tat ca Roles trong he thong
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_GET_ALL_ROLES (
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR
        SELECT role 
        FROM dba_roles
        WHERE role NOT LIKE 'ORA%'  -- Loc role he thong Oracle (Filter Oracle system roles)
          AND role NOT LIKE 'XDB%'
        ORDER BY role;
END;
/

-- 10.9 Kiem tra quyen hien tai cua User tren mot Bang
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_CHECK_USER_PERMISSION (
    p_username IN VARCHAR2,
    p_table    IN VARCHAR2,
    p_select   OUT NUMBER,
    p_insert   OUT NUMBER,
    p_update   OUT NUMBER,
    p_delete   OUT NUMBER
) IS
BEGIN
    -- Khoi tao gia tri ban dau (Initialize default values)
    p_select := 0; 
    p_insert := 0; 
    p_update := 0; 
    p_delete := 0;

    -- Quet cac quyen da cap cho user
    FOR r IN (
        SELECT PRIVILEGE 
        FROM dba_tab_privs 
        WHERE GRANTEE = p_username 
          AND TABLE_NAME = p_table
          AND OWNER = 'NAM_DOAN'
    ) LOOP
        IF r.PRIVILEGE = 'SELECT' THEN p_select := 1; END IF;
        IF r.PRIVILEGE = 'INSERT' THEN p_insert := 1; END IF;
        IF r.PRIVILEGE = 'UPDATE' THEN p_update := 1; END IF;
        IF r.PRIVILEGE = 'DELETE' THEN p_delete := 1; END IF;
    END LOOP;
END;
/

-- 10.9.1 Kiem tra quyen hien tai cua Role tren mot Bang
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_CHECK_ROLE_PERMISSION (
    p_role_name IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    OUT NUMBER,
    p_insert    OUT NUMBER,
    p_update    OUT NUMBER,
    p_delete    OUT NUMBER
) IS
BEGIN
    p_select := 0; p_insert := 0; p_update := 0; p_delete := 0;

    FOR r IN (
        SELECT PRIVILEGE 
        FROM dba_tab_privs 
        WHERE GRANTEE = p_role_name 
          AND TABLE_NAME = p_table
          AND OWNER = 'NAM_DOAN'
    ) LOOP
        IF r.PRIVILEGE = 'SELECT' THEN p_select := 1; END IF;
        IF r.PRIVILEGE = 'INSERT' THEN p_insert := 1; END IF;
        IF r.PRIVILEGE = 'UPDATE' THEN p_update := 1; END IF;
        IF r.PRIVILEGE = 'DELETE' THEN p_delete := 1; END IF;
    END LOOP;
END;
/

-- =========================================================================
-- 11. TINH NANG MO RONG - XAC THUC KHUON MAT & QR CODE
-- =========================================================================

-- 11.1 Them cot cho bang USERS (de luu anh khuon mat va ma QR)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (FACE_IMG BLOB, QR_CODE VARCHAR2(255))';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Cot da ton tai, bo qua
END;
/

-- 11.2 Package AUTH_EXT_PKG (Xac thuc mo rong - Face & QR)
CREATE OR REPLACE PACKAGE NAM_DOAN.AUTH_EXT_PKG AS

    -- Cap nhat Face Image cho user
    PROCEDURE P_UPDATE_FACE_IMG(
        p_username IN VARCHAR2,
        p_img      IN BLOB
    );
    
    -- Cap nhat QR Code cho user
    PROCEDURE P_UPDATE_QR_CODE(
        p_username IN VARCHAR2,
        p_qr       IN VARCHAR2
    );
    
    -- Lay ten user tu ma QR
    FUNCTION F_GET_USER_BY_QR(p_qr IN VARCHAR2) RETURN VARCHAR2;

    -- Lay tat ca Face Image de training/matching
    PROCEDURE P_GET_ALL_FACES(p_cursor OUT SYS_REFCURSOR);
    
    -- Lay thong tin dang nhap ma hoa (de App tu dong Login sau khi verify Face/QR)
    PROCEDURE P_GET_USER_CREDENTIALS(
        p_username   IN VARCHAR2,
        p_enc_user   OUT VARCHAR2,
        p_enc_pass   OUT VARCHAR2
    );

END AUTH_EXT_PKG;
/

CREATE OR REPLACE PACKAGE BODY NAM_DOAN.AUTH_EXT_PKG AS

    PROCEDURE P_UPDATE_FACE_IMG(
        p_username IN VARCHAR2,
        p_img      IN BLOB
    ) IS
    BEGIN
        UPDATE USERS 
        SET FACE_IMG = p_img 
        WHERE USER_NAME = p_username;
        COMMIT;
    END P_UPDATE_FACE_IMG;

    PROCEDURE P_UPDATE_QR_CODE(
        p_username IN VARCHAR2,
        p_qr       IN VARCHAR2
    ) IS
    BEGIN
        UPDATE USERS 
        SET QR_CODE = p_qr
        WHERE USER_NAME = p_username;
        COMMIT;
    END P_UPDATE_QR_CODE;

    FUNCTION F_GET_USER_BY_QR(p_qr IN VARCHAR2) RETURN VARCHAR2 IS
        v_username VARCHAR2(100);
    BEGIN
        SELECT USER_NAME INTO v_username
        FROM USERS
        WHERE QR_CODE = p_qr;
        
        RETURN v_username;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
        WHEN TOO_MANY_ROWS THEN
             -- In case of duplicate QRs, just return the first one found by implicit cursor logic (though strictly implicit cursor throws TOO_MANY_ROWS, but we just want to avoid the syntax error).
             -- Actually, implicit select into throws TOO_MANY_ROWS if > 1. 
             -- Better approach for 'First Row Only' without 12c syntax:
             RETURN NULL; 
    END F_GET_USER_BY_QR;

    PROCEDURE P_GET_ALL_FACES(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
        SELECT USER_NAME, FACE_IMG
        FROM USERS
        WHERE FACE_IMG IS NOT NULL;
    END P_GET_ALL_FACES;

    PROCEDURE P_GET_USER_CREDENTIALS(
        p_username   IN VARCHAR2,
        p_enc_user   OUT VARCHAR2,
        p_enc_pass   OUT VARCHAR2
    ) IS
    BEGIN
        SELECT USER_NAME, PASSWORD
        INTO p_enc_user, p_enc_pass
        FROM USERS
        WHERE USER_NAME = p_username;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_enc_user := NULL;
            p_enc_pass := NULL;
    END P_GET_USER_CREDENTIALS;

END AUTH_EXT_PKG;
/

-- Cap quyen thuc thi cho ROLE_USERS
GRANT EXECUTE ON NAM_DOAN.AUTH_EXT_PKG TO ROLE_USERS;


-- 10.4 Thu hoi quyen (REVOKE)
CREATE OR REPLACE PROCEDURE NAM_DOAN.P_REVOKE_PERMISSION (
    p_user      IN VARCHAR2,
    p_table     IN VARCHAR2,
    p_select    IN NUMBER,
    p_insert    IN NUMBER,
    p_update    IN NUMBER,
    p_delete    IN NUMBER
) AUTHID CURRENT_USER
IS
BEGIN
    IF p_select = 1 THEN 
        BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; EXCEPTION WHEN OTHERS THEN NULL; END; 
    END IF;
    IF p_insert = 1 THEN 
        BEGIN EXECUTE IMMEDIATE 'REVOKE INSERT ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; EXCEPTION WHEN OTHERS THEN NULL; END; 
    END IF;
    IF p_update = 1 THEN 
        BEGIN EXECUTE IMMEDIATE 'REVOKE UPDATE ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; EXCEPTION WHEN OTHERS THEN NULL; END; 
    END IF;
    IF p_delete = 1 THEN 
        BEGIN EXECUTE IMMEDIATE 'REVOKE DELETE ON NAM_DOAN.' || p_table || ' FROM "' || p_user || '"'; EXCEPTION WHEN OTHERS THEN NULL; END; 
    END IF;
END;
/


-- =========================================================================
-- 12. TINH NANG GIAM SAT (AUDITING)
-- =========================================================================

-- 12.1 Lay danh sach tat ca User dang hoat dong
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_SELECT_ALL_USERS (
    v_out OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN v_out FOR
        SELECT username
        FROM dba_users
        WHERE account_status = 'OPEN'
          AND username NOT IN ('SYS', 'SYSTEM', 'OUTLN', 'XDB', 'DBSNMP', 'LBACSYS');
END;
/

-- 12.2 Bat Audit cho User cu the
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_CREATE_AUDIT (
    p_statement IN VARCHAR2,  -- Loai hoat dong: SELECT, INSERT, UPDATE, DELETE, etc.
    p_username  IN VARCHAR2   -- Ten user can giam sat
) 
IS
BEGIN
    -- Thuc thi lenh AUDIT (Always use quotes for username)
    EXECUTE IMMEDIATE 'AUDIT ' || p_statement || ' BY "' || p_username || '"';
    
    DBMS_OUTPUT.PUT_LINE('Audit created for "' || p_username || '"');
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 
            'Error creating audit for "' || p_username || '": ' || SQLERRM);
END SP_CREATE_AUDIT;
/

-- 12.3 Tat Audit cho User cu the
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_DROP_AUDIT (
    p_statement IN VARCHAR2,  -- Loai hoat dong: SELECT, INSERT, UPDATE, DELETE, etc.
    p_username  IN VARCHAR2   -- Ten user can bo giam sat
) 
IS
BEGIN
    -- Thuc thi lenh NOAUDIT (Always use quotes for username)
    EXECUTE IMMEDIATE 'NOAUDIT ' || p_statement || ' BY "' || p_username || '"';
    
    DBMS_OUTPUT.PUT_LINE('Audit removed for "' || p_username || '"');
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 
            'Error removing audit for "' || p_username || '": ' || SQLERRM);
END SP_DROP_AUDIT;
/

-- 12.4 Kiem tra cac Audit hien tai cua User
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_LIST_USER_AUDITS (
    p_username IN VARCHAR2,       -- Ten user can kiem tra
    p_result   OUT SYS_REFCURSOR  -- Ket qua tra ve
)
AS
BEGIN
    -- Lay tat ca cac audit option da duoc cau hinh cho user
    OPEN p_result FOR
        SELECT *
        FROM dba_obj_audit_opts
        WHERE OWNER = UPPER(p_username);
END;
/

-- 12.5 Lay danh sach tat ca cac bang (cho Audit)
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_SELECT_ALL_TABLES (
    p_out OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_out FOR
         SELECT table_name 
         FROM all_tables 
         WHERE owner = 'NAM_DOAN' 
         ORDER BY table_name;
END;
/

-- 12.6 Create FGA Audit
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_CREATE_FGA_AUDIT (
    p_username   IN VARCHAR2,
    p_table_name IN VARCHAR2,
    p_actions    IN VARCHAR2
)
IS
    v_policy_name VARCHAR2(100);
BEGIN
    v_policy_name := 'FGA_' || p_table_name || '_' || p_username;
    
    -- Xoa policy cu neu ton tai (tranh loi)
    BEGIN
        DBMS_FGA.DROP_POLICY(
            object_schema => 'NAM_DOAN', 
            object_name   => p_table_name, 
            policy_name   => v_policy_name
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    DBMS_FGA.ADD_POLICY(
        object_schema   => 'NAM_DOAN',
        object_name     => p_table_name,
        policy_name     => v_policy_name,
        audit_condition => 'SYS_CONTEXT(''USERENV'', ''SESSION_USER'') = ''' || p_username || '''',
        statement_types => p_actions
    );
END;
/

-- 12.7 Drop FGA Audit
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_DROP_FGA_AUDIT (
    p_username   IN VARCHAR2,
    p_table_name IN VARCHAR2
)
IS
    v_policy_name VARCHAR2(100);
BEGIN
    v_policy_name := 'FGA_' || p_table_name || '_' || p_username;
    
    DBMS_FGA.DROP_POLICY(
        object_schema => 'NAM_DOAN',
        object_name   => p_table_name,
        policy_name   => v_policy_name
    );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 12.8 Get Audit Logs
CREATE OR REPLACE PROCEDURE NAM_DOAN.SP_GET_AUDIT_LOGS_BY_USER (
    p_username IN VARCHAR2,
    p_cursor   OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_cursor FOR
        SELECT timestamp, db_user, object_name, sql_text, statement_type, policy_name 
        FROM dba_fga_audit_trail
        WHERE db_user = p_username
        ORDER BY timestamp DESC;
END;
/


-- =========================================================================
-- 13. CAP QUYEN THUC THI CHO CAC PROCEDURES PHAN QUYEN
-- =========================================================================

-- Cap quyen execute cho PUBLIC (tat ca users co the goi)
GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_TABLES TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_DB_USERS TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_GRANT_PERMISSION TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_REVOKE_PERMISSION TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_CREATE_ROLE TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_GRANT_PERMISSION_TO_ROLE TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_GRANT_ROLE_TO_USER TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_ROLES TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.P_CHECK_USER_PERMISSION TO PUBLIC;

-- Hoac chi cap cho ROLE_USERS (khuyen nghi hon cho bao mat)
-- GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_TABLES TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_DB_USERS TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_GRANT_PERMISSION TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_REVOKE_PERMISSION TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_CREATE_ROLE TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_GRANT_PERMISSION_TO_ROLE TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_GRANT_ROLE_TO_USER TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_GET_ALL_ROLES TO ROLE_USERS;
-- GRANT EXECUTE ON NAM_DOAN.P_CHECK_USER_PERMISSION TO ROLE_USERS;

-- =========================================================================
-- 11. PACKAGE AUTH_EXT_PKG (FACE ID & QR CODE)
-- =========================================================================

CREATE OR REPLACE PACKAGE NAM_DOAN.AUTH_EXT_PKG AS
    PROCEDURE P_UPDATE_FACE_IMG(p_username IN VARCHAR2, p_img IN BLOB);
    PROCEDURE P_UPDATE_QR_CODE(p_username IN VARCHAR2, p_qr IN VARCHAR2);
    FUNCTION F_GET_USER_BY_QR(p_qr IN VARCHAR2) RETURN VARCHAR2;
    PROCEDURE P_GET_ALL_FACES(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE P_GET_USER_CREDENTIALS(p_username IN VARCHAR2, p_enc_user OUT VARCHAR2, p_enc_pass OUT VARCHAR2);
END AUTH_EXT_PKG;
/

CREATE OR REPLACE PACKAGE BODY NAM_DOAN.AUTH_EXT_PKG AS

    PROCEDURE P_UPDATE_FACE_IMG(p_username IN VARCHAR2, p_img IN BLOB) IS
    BEGIN
        UPDATE USERS SET FACE_IMG = p_img WHERE USER_NAME = p_username;
        COMMIT;
    END P_UPDATE_FACE_IMG;

    PROCEDURE P_UPDATE_QR_CODE(p_username IN VARCHAR2, p_qr IN VARCHAR2) IS
    BEGIN
        UPDATE USERS SET QR_CODE = p_qr WHERE USER_NAME = p_username;
        COMMIT;
    END P_UPDATE_QR_CODE;

    FUNCTION F_GET_USER_BY_QR(p_qr IN VARCHAR2) RETURN VARCHAR2 IS
        v_username VARCHAR2(100);
    BEGIN
        SELECT USER_NAME INTO v_username FROM USERS WHERE QR_CODE = p_qr;
        RETURN v_username;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
    END F_GET_USER_BY_QR;

    PROCEDURE P_GET_ALL_FACES(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR SELECT USER_NAME, FACE_IMG FROM USERS WHERE FACE_IMG IS NOT NULL;
    END P_GET_ALL_FACES;

    PROCEDURE P_GET_USER_CREDENTIALS(p_username IN VARCHAR2, p_enc_user OUT VARCHAR2, p_enc_pass OUT VARCHAR2) IS
    BEGIN
        SELECT USER_NAME, PASSWORD INTO p_enc_user, p_enc_pass FROM USERS WHERE USER_NAME = p_username;
    EXCEPTION WHEN NO_DATA_FOUND THEN p_enc_user := NULL; p_enc_pass := NULL;
    END P_GET_USER_CREDENTIALS;
    
END AUTH_EXT_PKG;
/

-- Cap quyen cho ROLE_USERS
GRANT EXECUTE ON NAM_DOAN.AUTH_EXT_PKG TO ROLE_USERS;

-- Cap quyen cho cac procedure Audit moi
GRANT EXECUTE ON NAM_DOAN.SP_SELECT_ALL_USERS TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.SP_SELECT_ALL_TABLES TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.SP_CREATE_FGA_AUDIT TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.SP_DROP_FGA_AUDIT TO PUBLIC;
GRANT EXECUTE ON NAM_DOAN.SP_GET_AUDIT_LOGS_BY_USER TO PUBLIC;


